local _, NS = ...
local L = {}
NS.L = L

--[[
    Want to help Translate Diminish?
    https://wow.curseforge.com/projects/diminish/localization/

    * THE REST OF THIS FILE IS AUTOMATICALLY GENERATED *
]]

L["DISARM"] = "Disarm"
L["DISORIENT"] = "Disorient"
L["ERROR_LOADOPTIONS"] = "Error loading Diminish_Options. It's most likely set to disabled."
L["INCAPACITATE"] = "Incapacitate"
L["ROOT"] = "Root"
L["SILENCE"] = "Silence"
L["STUN"] = "Stun"
L["TAUNT"] = "Taunt"
