local _, NS = ...
local L = {}
NS.L = L

--[[
    Want to help Translate Diminish?
    https://wow.curseforge.com/projects/diminish/localization/

    * THE REST OF THIS FILE IS AUTOMATICALLY GENERATED *
]]

L["ANCHORDRAG"] = [=[%s
Grows: %s]=]
L["ARENA"] = "Arena"
L["CATEGORIES_TOOLTIP"] = "Toggle category for tracking."
L["COLORBLIND"] = "Show Indicators Using Text"
L["COLORBLIND_TOOLTIP"] = [=[Show DR indicators using text only instead of colors. Works best when using larger icons. May not work with some Masque skins.

Disabling "%s" will put the indicator text in the center of the icon.]=]
L["COMBATLOCKDOWN_ERROR"] = "Must leave combat before doing that."
L["COMPACTFRAMES_ERROR"] = "Unable to test raid frames while not in a group."
L["COPY"] = "Copy"
L["COPY_TOOLTIP"] = "Copies settings from one existing profile into the currently active profile."
L["CURRENT_PROFILE"] = "Current Profile: |cffFFEB00%s|r"
L["DEFAULT"] = "Default"
L["DELETE"] = "Delete"
L["DELETE_TOOLTIP"] = "Delete an existing profile. Deletes and resets to default if profile chosen is the current active one."
L["DISPLAYMODE"] = "Start Cooldown on Aura Applied"
L["DISPLAYMODE_TOOLTIP"] = "Start DR timers on aura applied instead of removed."
L["ENABLED"] = "Enabled"
L["ENABLED_TOOLTIP"] = "Enable or disable DR tracking for this specific unit frame."
L["FOCUS"] = "Focus"
L["GROWLEFT"] = "Grow Left"
L["GROWLEFT_TOOLTIP"] = "Toggle if active icons move left or right from anchor."
L["HEADER_CATEGORIES"] = "Enabled Categories"
L["HEADER_COOLDOWN"] = "Cooldown"
L["HEADER_ICONS"] = "Icons"
L["HEADER_MISC"] = "Misc"
L["HEADER_PROFILES"] = "Create and set configuration profiles so you can have different settings for every character. Creating new profiles will consume more memory so try to reuse profiles whenever possible. See tooltips for detailed info."
L["HEADER_UNITFRAME"] = "Configuration for %s frame tracking."
L["HEADER_ZONE"] = "Enable in Zone"
L["ICONPADDING"] = "Frame Padding"
L["ICONPADDING_TOOLTIP"] = "Set padding between all active DR icons."
L["ICONSIZE"] = "Frame Size"
L["ICONSIZE_TOOLTIP"] = "Set size of the DR icons."
L["LEFT"] = "left"
L["NEWPROFILE"] = "Create New Profile"
L["NEWPROFILE_TOOLTIP"] = "Create a new profile with current active settings as a starting point."
L["PARTY"] = "Party"
L["PLAYER"] = "Player"
L["PROFILEACTIVE"] = "That profile is already active."
L["PROFILEEXISTS"] = "Profile with that name already exists."
L["PROFILES"] = "Profiles"
L["RESETPOS"] = "Reset Position"
L["RESETPOS_TOOLTIP"] = "Reset icon positions for this unitframe back to default values."
L["RESETPROFILE"] = "Reset Profile"
L["RESETPROFILE_TOOLTIP"] = "Reset current active profile to default settings."
L["RIGHT"] = "right"
L["SELECTBORDER"] = "Select Border Style"
L["SELECTBORDER_TOOLTIP"] = "Choose between different border textures for the DR icons. You may also skin the icons using Masque."
L["SELECTPROFILE"] = "Select Profile"
L["SELECTPROFILE_TOOLTIP"] = "Select a profile to use, copy or delete."
L["SHOWCATEGORYTEXT"] = "Display DR Category Label"
L["SHOWCATEGORYTEXT_TOOLTIP"] = "Show text above a timer that displays what DR category a timer belongs to."
L["SPELLBOOKTEXTURES"] = "Show Own Textures Only"
L["SPELLBOOKTEXTURES_TOOLTIP"] = [=[DR icons for enemies will only use spell textures found in your own spellbook that matches the triggered category if available.

(Spellbook textures will be set & saved only after you have yourself casted a CC ability once for that category)]=]
L["STOP"] = "Stop"
L["TARGET"] = "Target"
L["TARGETTIP"] = "Target/focus yourself to see all frames."
L["TEST"] = "Test Frames"
L["TEST_TOOLTIP"] = "Test all enabled DR frames."
L["TEXTURE_BRIGHT"] = "Bright"
L["TEXTURE_GLOW"] = "Default, with glow"
L["TEXTURE_NONE"] = "None"
L["TIMERCOLORS"] = "Show Countdown Indicator"
L["TIMERCOLORS_TOOLTIP"] = "Toggles DR indicator coloring of the countdown text."
L["TIMERSWIPE"] = "Show Swipe for Cooldowns"
L["TIMERSWIPE_TOOLTIP"] = "Toggles the cooldown swipe animation for all frames."
L["TIMERTEXT"] = "Show Countdown for Cooldowns"
L["TIMERTEXT_TOOLTIP"] = [=[Toggles the Blizzard cooldown countdown text for all frames.

(Esc -> Interface -> ActionBars -> Show Numbers for Cooldowns)]=]
L["TIMERTEXTSIZE"] = "Countdown Size"
L["TIMERTEXTSIZE_TOOLTIP"] = "Set font size of the timer countdown text."
L["TRACKNPCS"] = "Enable Tracking for PvE"
L["TRACKNPCS_TOOLTIP"] = [=[Show stun & taunt DR timers on mobs. Also shows all timers on player pets. (Target/focus)

Enabling this may drastically increase memory usage in large Battlegrounds.]=]
L["UNLOCK"] = "Unlock/Move Frames"
L["UNLOCK_TOOLTIP"] = "Toggle enabled frames for moving. Drag the red boxes to move icon spawn points."
L["USEPROFILE"] = "Use"
L["USEPROFILE_TOOLTIP"] = [=[Set an existing profile to use for this character.

Any modifications to the profile will affect all characters using the profile.]=]
L["WATCHFRIENDLY"] = "Show Friendly DRs"
L["WATCHFRIENDLY_TOOLTIP"] = [=[Toggle DR tracking for friendly players. (Cast by enemy onto friendly)

Enabling this will drastically increase memory usage in large Battlegrounds.]=]
L["ZONE_ARENA"] = "Arena"
L["ZONE_BATTLEGROUNDS"] = "Battlegrounds & Brawls"
L["ZONE_DUNGEONS"] = "Dungeons & Raids"
L["ZONE_OUTDOORS"] = "Outdoors"
L["ZONES_TOOLTIP"] = "Enable tracking for this zone."
